import { Open_Sans } from "next/font/google";
import "@/styles/globals.css";

import ThirdPartyProvider from "@/contexts/ThirdPartyProvider";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ThirdPartyProvider>{children}</ThirdPartyProvider>
      </body>
    </html>
  );
}
